"""delivery settings

Revision ID: 583a4a7ce38a
Revises: e810f02c155b
Create Date: 2026-09-23 22:50:41.014064
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import trade_news.db.schema

revision: str = "583a4a7ce38a"
down_revision: str | None = "e810f02c155b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=True)
        )
        batch_op.create_index(batch_op.f("ix_deliveries_sent_at"), ["sent_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_deliveries_status_channel"), ["status", "channel"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deliveries_status_channel"))
        batch_op.drop_index(batch_op.f("ix_deliveries_sent_at"))
        batch_op.drop_column("created_at")

    op.drop_table("settings")
    # ### end Alembic commands ###
