"""sectors

Revision ID: af00c6a4fa19
Revises: ec87750fea2e
Create Date: 2026-09-27 10:28:56.947389
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import trade_news.db.schema

revision: str = "af00c6a4fa19"
down_revision: str | None = "ec87750fea2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_sectors",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "annotation_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("sector", sa.Text(), nullable=False),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_item_sectors_annotation_id_annotations"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_item_sectors_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_sectors")),
    )
    with op.batch_alter_table("item_sectors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_item_sectors_item_id"), ["item_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_item_sectors_sector_industry"), ["sector", "industry"], unique=False
        )

    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("industry", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("sic", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "sector_checked_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=True
            )
        )
        batch_op.create_index(
            batch_op.f("ix_assets_sector_industry"), ["sector", "industry"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # recreate="never": SQLite drops columns in place (3.35+); recreating assets would break
    # the foreign keys that point at it.
    with op.batch_alter_table("assets", schema=None, recreate="never") as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_sector_industry"))
        batch_op.drop_column("sector_checked_at")
        batch_op.drop_column("sic")
        batch_op.drop_column("industry")

    with op.batch_alter_table("item_sectors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_sectors_sector_industry"))
        batch_op.drop_index(batch_op.f("ix_item_sectors_item_id"))

    op.drop_table("item_sectors")
    # ### end Alembic commands ###
