"""subscribers

Revision ID: c46d4c335bf5
Revises: cc1df9b2f6b5
Create Date: 2026-09-23 20:53:07.778375
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import trade_news.db.schema

revision: str = "c46d4c335bf5"
down_revision: str | None = "cc1df9b2f6b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscribers",
        sa.Column("chat_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("chat_type", sa.String(length=16), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("subscribed_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "unsubscribed_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("unsubscribe_reason", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("chat_id", name=op.f("pk_subscribers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscribers")
    # ### end Alembic commands ###
