"""initial schema

Revision ID: cc1df9b2f6b5
Revises:
Create Date: 2026-09-23 20:28:21.153231
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import trade_news.db.schema

revision: str = "cc1df9b2f6b5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "asset_class",
            sa.Enum(
                "equity",
                "fx",
                "crypto",
                "commodity",
                "index",
                "rates",
                "macro",
                name="asset_class",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("exchange", sa.Text(), nullable=True),
        sa.Column("base_ccy", sa.Text(), nullable=True),
        sa.Column("quote_ccy", sa.Text(), nullable=True),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("asset_class", "symbol", name=op.f("uq_assets_asset_class_symbol")),
    )
    op.create_table(
        "collector_runs",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("started_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column("finished_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("fetched", sa.Integer(), nullable=False),
        sa.Column("inserted", sa.Integer(), nullable=False),
        sa.Column("seen_before", sa.Integer(), nullable=False),
        sa.Column("dedup_merged", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collector_runs")),
    )
    with op.batch_alter_table("collector_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_collector_runs_source_started_at"),
            ["source", "started_at"],
            unique=False,
        )

    op.create_table(
        "collector_state",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "cursor",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("updated_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("source", name=op.f("pk_collector_state")),
    )
    op.create_table(
        "econ_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("event_name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column("scheduled_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column("actual", sa.Float(), nullable=True),
        sa.Column("forecast", sa.Float(), nullable=True),
        sa.Column("previous", sa.Float(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("importance", sa.SmallInteger(), nullable=True),
        sa.Column("snapshot_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "surprise", sa.Float(), sa.Computed("actual - forecast", persisted=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_econ_events")),
    )
    with op.batch_alter_table("econ_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_econ_events_event_name_country_scheduled_at_snapshot_at"),
            ["event_name", "country", "scheduled_at", "snapshot_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_econ_events_scheduled_at"), ["scheduled_at"], unique=False
        )

    op.create_table(
        "rate_expectations",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("central_bank", sa.Text(), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("snapshot_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_expectations")),
        sa.UniqueConstraint(
            "central_bank",
            "meeting_date",
            "snapshot_at",
            "outcome",
            name=op.f("uq_rate_expectations_central_bank_meeting_date_snapshot_at_outcome"),
        ),
    )
    op.create_table(
        "raw_items",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_item_id", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("published_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "raw_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_items")),
        sa.UniqueConstraint(
            "source",
            "source_item_id",
            "content_hash",
            name=op.f("uq_raw_items_source_source_item_id_content_hash"),
        ),
    )
    op.create_table(
        "asset_aliases",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("asset_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("lang", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_asset_aliases_asset_id_assets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_aliases")),
        sa.UniqueConstraint("alias", "lang", name=op.f("uq_asset_aliases_alias_lang")),
    )
    with op.batch_alter_table("asset_aliases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_aliases_asset_id"), ["asset_id"], unique=False)

    op.create_table(
        "items",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "raw_item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_item_id", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("title_norm", sa.Text(), nullable=True),
        sa.Column("title_hash", sa.String(length=64), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("published_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "dedup_group_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("dedup_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["raw_item_id"], ["raw_items.id"], name=op.f("fk_items_raw_item_id_raw_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint(
            "source", "source_item_id", name=op.f("uq_items_source_source_item_id")
        ),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_items_canonical_url"), ["canonical_url"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_items_dedup_group_id"), ["dedup_group_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_items_published_at"), ["published_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_title_hash"), ["title_hash"], unique=False)

    op.create_table(
        "prices",
        sa.Column("asset_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("interval", sa.String(length=8), nullable=False),
        sa.Column("ts", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_prices_asset_id_assets")
        ),
        sa.PrimaryKeyConstraint("asset_id", "interval", "ts", name=op.f("pk_prices")),
    )
    op.create_table(
        "annotations",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("created_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "cost_estimate", sa.Numeric(precision=12, scale=6, asdecimal=False), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_annotations_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annotations")),
        sa.UniqueConstraint(
            "item_id", "prompt_version", name=op.f("uq_annotations_item_id_prompt_version")
        ),
    )
    op.create_table(
        "deliveries",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("sent_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=True),
        sa.Column("message_id", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_deliveries_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint("item_id", "channel", name=op.f("uq_deliveries_item_id_channel")),
    )
    op.create_table(
        "asset_resolution_queue",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "annotation_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "asset_class",
            sa.Enum(
                "equity",
                "fx",
                "crypto",
                "commodity",
                "index",
                "rates",
                "macro",
                name="asset_class",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("symbol_or_name", sa.Text(), nullable=False),
        sa.Column("created_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "resolved_asset_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("resolved_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_asset_resolution_queue_annotation_id_annotations"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_asset_resolution_queue_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["resolved_asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_resolution_queue_resolved_asset_id_assets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_resolution_queue")),
    )
    with op.batch_alter_table("asset_resolution_queue", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_asset_resolution_queue_resolved_at"), ["resolved_at"], unique=False
        )

    op.create_table(
        "item_assets",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "annotation_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "asset_class",
            sa.Enum(
                "equity",
                "fx",
                "crypto",
                "commodity",
                "index",
                "rates",
                "macro",
                name="asset_class",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "scope",
            sa.Enum(
                "market_wide",
                "group",
                "specific",
                name="scope",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("asset_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("group_label", sa.Text(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum(
                "bullish",
                "bearish",
                "neutral",
                name="direction",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("importance", sa.SmallInteger(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2, asdecimal=False), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.CheckConstraint(
            "confidence between 0 and 1", name=op.f("ck_item_assets_confidence_range")
        ),
        sa.CheckConstraint(
            "importance between 1 and 5", name=op.f("ck_item_assets_importance_range")
        ),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_item_assets_annotation_id_annotations"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_item_assets_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_item_assets_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_assets")),
    )
    with op.batch_alter_table("item_assets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_item_assets_asset_class_scope"), ["asset_class", "scope"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_item_assets_asset_id"),
            ["asset_id"],
            unique=False,
            sqlite_where=sa.text("asset_id is not null"),
            postgresql_where=sa.text("asset_id is not null"),
        )
        batch_op.create_index(batch_op.f("ix_item_assets_item_id"), ["item_id"], unique=False)

    op.create_table(
        "item_relevance",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "annotation_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "relevance_type",
            sa.Enum(
                "immediate",
                "scheduled",
                "window",
                "unknown",
                name="relevance_type",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("relevant_from", trade_news.db.schema.UTCDateTime(timezone=True), nullable=True),
        sa.Column("relevant_to", trade_news.db.schema.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "date_precision",
            sa.Enum(
                "exact",
                "day",
                "month",
                "quarter",
                "unknown",
                name="date_precision",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("raw_phrase", sa.Text(), nullable=True),
        sa.Column("anchor_ts", trade_news.db.schema.UTCDateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=16), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_item_relevance_annotation_id_annotations"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_item_relevance_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_relevance")),
    )
    with op.batch_alter_table("item_relevance", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_item_relevance_item_id"), ["item_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_item_relevance_relevance_type_relevant_from"),
            ["relevance_type", "relevant_from"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_item_relevance_relevant_from"), ["relevant_from"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item_relevance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_relevance_relevant_from"))
        batch_op.drop_index(batch_op.f("ix_item_relevance_relevance_type_relevant_from"))
        batch_op.drop_index(batch_op.f("ix_item_relevance_item_id"))

    op.drop_table("item_relevance")
    with op.batch_alter_table("item_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_assets_item_id"))
        batch_op.drop_index(
            batch_op.f("ix_item_assets_asset_id"),
            sqlite_where=sa.text("asset_id is not null"),
            postgresql_where=sa.text("asset_id is not null"),
        )
        batch_op.drop_index(batch_op.f("ix_item_assets_asset_class_scope"))

    op.drop_table("item_assets")
    with op.batch_alter_table("asset_resolution_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_resolution_queue_resolved_at"))

    op.drop_table("asset_resolution_queue")
    op.drop_table("deliveries")
    op.drop_table("annotations")
    op.drop_table("prices")
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_title_hash"))
        batch_op.drop_index(batch_op.f("ix_items_published_at"))
        batch_op.drop_index(batch_op.f("ix_items_dedup_group_id"))
        batch_op.drop_index(batch_op.f("ix_items_canonical_url"))

    op.drop_table("items")
    with op.batch_alter_table("asset_aliases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_aliases_asset_id"))

    op.drop_table("asset_aliases")
    op.drop_table("raw_items")
    op.drop_table("rate_expectations")
    with op.batch_alter_table("econ_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_econ_events_scheduled_at"))
        batch_op.drop_index(
            batch_op.f("ix_econ_events_event_name_country_scheduled_at_snapshot_at")
        )

    op.drop_table("econ_events")
    op.drop_table("collector_state")
    with op.batch_alter_table("collector_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collector_runs_source_started_at"))

    op.drop_table("collector_runs")
    op.drop_table("assets")
    # ### end Alembic commands ###
