"""annotation support

Revision ID: e810f02c155b
Revises: c46d4c335bf5
Create Date: 2026-09-23 21:55:05.144809
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import trade_news.db.schema

revision: str = "e810f02c155b"
down_revision: str | None = "c46d4c335bf5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_calls",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("started_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("n_items", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "cost_estimate", sa.Numeric(precision=12, scale=6, asdecimal=False), nullable=True
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_calls_model_started_at"), ["model", "started_at"], unique=False
        )

    op.create_table(
        "annotation_dead_letters",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("created_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_annotation_dead_letters_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annotation_dead_letters")),
        sa.UniqueConstraint(
            "item_id",
            "prompt_version",
            name=op.f("uq_annotation_dead_letters_item_id_prompt_version"),
        ),
    )
    with op.batch_alter_table("asset_aliases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("alias_norm", sa.Text(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_asset_aliases_alias_norm"), ["alias_norm"], unique=False
        )

    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cik", sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f("ix_assets_cik"), ["cik"], unique=False)
        batch_op.create_index(batch_op.f("ix_assets_symbol"), ["symbol"], unique=False)

    with op.batch_alter_table("item_assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("raw_symbol", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item_assets", schema=None) as batch_op:
        batch_op.drop_column("raw_symbol")

    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_symbol"))
        batch_op.drop_index(batch_op.f("ix_assets_cik"))
        batch_op.drop_column("cik")

    with op.batch_alter_table("asset_aliases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_aliases_alias_norm"))
        batch_op.drop_column("alias_norm")

    op.drop_table("annotation_dead_letters")
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_calls_model_started_at"))

    op.drop_table("llm_calls")
    # ### end Alembic commands ###
