"""macro observations

Revision ID: ec87750fea2e
Revises: 583a4a7ce38a
Create Date: 2026-09-25 18:55:11.259089
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401  (autogenerate renders JSONB(astext_type=Text()))

import trade_news.db.schema

revision: str = "ec87750fea2e"
down_revision: str | None = "583a4a7ce38a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "macro_observations",
        sa.Column("series_id", sa.Text(), nullable=False),
        sa.Column("obs_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("fetched_at", trade_news.db.schema.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("series_id", "obs_date", name=op.f("pk_macro_observations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("macro_observations")
    # ### end Alembic commands ###
